server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: ms-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: api-movie
          uri: lb://api-movie
          predicates:
            - Path=/api/v1/movies/**
        - id: api-catalog
          uri: lb://api-catalog
          predicates:
            - Path=/api/v1/catalog/**

info:
  app:
    name: ${spring.application.name}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway